# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: no
  user: root

  tasks:

  - name: copy over minimal inputrc (root)
    copy:
      src: /home/ghz/ansible_playbooks/plates/.inputrc
      dest: /root/.inputrc
      owner: root
      group: root
      mode: 0644
      force: false
    tags:
      - configs

  - name: copy over minimal inputrc (user)
    copy:
      src: /home/ghz/ansible_playbooks/plates/.inputrc
      dest: /home/ghz/.inputrc
      owner: ghz
      group: ghz
      mode: 0644
      force: false
    tags:
      - configs
    when: inventory_hostname in groups['wxps']

  - name: copy over minimal vimrc (root)
    copy:
      src: /home/ghz/env/.vimrc
      dest: /root/.vimrc
      owner: root
      group: root
      mode: 0644
      force: false
    tags:
      - configs

  - name: copy over minimal vimrc (user)
    copy:
      src: /home/ghz/env/.vimrc
      dest: /home/ghz/.vimrc
      owner: ghz
      group: ghz
      mode: 0644
      force: false
    tags:
      - configs
    when: inventory_hostname in groups['wxps']
