# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

  - name: copy over minimal inputrc (root)
    copy:
      src: /home/ghz/repos/ansible_playbooks/plates/.inputrc
      dest: /root/.inputrc
      owner: root
      mode: 0644
      force: false
    tags:
      - configs

  - name: copy over minimal inputrc (user)
    copy:
      src: /home/ghz/repos/ansible_playbooks/plates/.inputrc
      dest: /home/ghz/.inputrc
      owner: ghz
      group: ghz
      mode: 0644
      force: false
    when: inventory_hostname in groups['wxps']
    tags:
      - configs

  - name: copy over minimal vimrc (root)
    copy:
      src: /home/ghz/env/.vimrc
      dest: /root/.vimrc
      owner: root
      mode: 0644
      force: false
    tags:
      - configs

  - name: copy over minimal vimrc (user)
    copy:
      src: /home/ghz/env/.vimrc
      dest: /home/ghz/.vimrc
      owner: ghz
      group: ghz
      mode: 0644
      force: false
    when: inventory_hostname in groups['wxps']
    tags:
      - configs

  - name: config prompt (root)
    lineinfile:
      dest: /root/.profile
      insertafter: 'export PATH'
      line: 'PS1="[\u@\h \W]# "'
    when: ansible_system == 'OpenBSD'
    tags:
      - configs

  - name: config shell history (root)
    lineinfile:
      dest: /root/.profile
      insertafter: 'export PATH'
      line: 'HISTFILE="$HOME/.sh_history"'
    when: ansible_system == 'OpenBSD'
    tags:
      - configs
