# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---
- hosts: pis
  gather_facts: yes
  user: root

  tasks:

  - name: add sshfs packages (deb)
    apt:
      name: sshfs
      state: present
    tags:
      - packages
    when: ansible_os_family == 'Debian'

  - name: add sshfs packages (alp)
    apk:
      name: sshfs
      state: present
      update_cache: yes
    tags:
      - packages
    when: ansible_os_family == 'Alpine'

  # make sre we don't try to change the perms on mounted mounts
  - name: unmount sshfs mount point
    mount:
      name: /import/home/ghz
      src: ghz@fs1:/zspace/pi/ghz
      # fstype: fuse.sshfs
      # opts: delay_connect,_netdev,rw,nosuid,nodev,allow_other
      state: unmounted

  - name: destroy everything. gawd this is dumb.
    file:
      state: absent
      path: /import
    when: inventory_hostname in groups['pis']

  - name: add mount point dir (1/2)
    file:
      dest: /import/home
      owner: root
      group: root
      state: directory
      mode: 0755

  # we've observed the following problem
  # 1. systemd automount whatever cocks up and looses the mount.
  # 2. the box writes like normal, but now in the mount point.
  # 3. systemd can't remount cuz the mountpoint isn't empty.
  # so to work around we make the home dir mount point not writable to the user
  # this is dumb. real dumb.
  - name: add mount point dir (2/2)
    file:
      dest: /import/home/ghz
      owner: root
      group: root
      state: directory
      mode: 0000

  - name: make sure root has a key
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_type: ed25519

  - name: add sshfs mount point
    mount:
      name: /import/home/ghz
      src: ghz@fs1:/zspace/pi/ghz
      fstype: fuse.sshfs
      opts: delay_connect,_netdev,rw,nosuid,nodev,allow_other
      state: mounted
