# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---
- hosts: pis
  gather_facts: yes
  user: root

  tasks:

  - name: add sshfs packages (deb)
    apt:
      name: sshfs
      state: present
    tags:
      - packages
      - sshfs
    when: ansible_os_family == 'Debian'

  - name: add sshfs packages (alp)
    apk:
      name: sshfs
      state: present
      update_cache: yes
    tags:
      - packages
      - sshfs
    when: ansible_os_family == 'Alpine'

  - name: add sshfs packages (OpenBSD)
    openbsd_pkg:
      name: sshfs-fuse
      state: present
    tags:
      - packages
      - sshfs
    when: ansible_os_family == 'OpenBSD'

  # make sre we don't try to change the perms on mounted mounts
  - name: unmount sshfs mount point
    mount:
      name: /import/home/ghz
      src: ghz@fs1:/zspace/pi/ghz
      # fstype: fuse.sshfs
      # opts: delay_connect,_netdev,rw,nosuid,nodev,allow_other
      state: unmounted
    when: ansible_system == 'Linux'
    tags:
      - sshfs

  - name: destroy everything. gawd this is dumb.
    file:
      state: absent
      path: /import
    when: inventory_hostname in groups['pis'] and ansible_system == 'Linux'
    tags:
      - sshfs

  - name: add mount point dir (1/2)
    file:
      dest: /import/home
      owner: root
      state: directory
      mode: 0755
    tags:
      - sshfs
      - mountpoint

  # we've observed the following problem in linux
  # 1. systemd automount whatever cocks up and looses the mount.
  # 2. the box writes like normal, but now in the mount point.
  # 3. systemd can't remount cuz the mountpoint isn't empty.
  # so to work around we make the home dir mount point not writable to the user
  # this is dumb. real dumb.
  - name: add mount point dir (2/2)
    file:
      dest: /import/home/ghz
      owner: root
      state: directory
      mode: 0000
    when: ansible_system == 'Linux'
    tags:
      - sshfs
      - mountpoint

  - name: add mount point dir (2/2)
    file:
      dest: /import/home/ghz
      state: directory
    when: ansible_system == 'OpenBSD'
    tags:
      - sshfs
      - mountpoint

  - name: make sure root has a key
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_type: ed25519
    tags:
      - sshfs

  - name: add sshfs mount point
    mount:
      name: /import/home/ghz
      src: ghz@fs1:/zspace/pi/ghz
      fstype: fuse.sshfs
      opts: delay_connect,_netdev,rw,nosuid,nodev,allow_other
      state: mounted
    when: ansible_system == 'Linux'
    tags:
      - sshfs

  - name: add sshfs mount line to rc.local
    lineinfile:
      dest: /etc/rc.local
      line: '/usr/local/bin/sshfs -o allow_other,reconnect ghz@bobble:/zspace/pi/ghz /import/home/ghz'
    when: ansible_system == 'OpenBSD'
    tags:
      - sshfs
      - rc.local

  - name: mount remote home (OpenBSD)
    shell:
      cmd: '[ -f /import/home/ghz/.zshrc ] || /usr/local/bin/sshfs -o allow_other,reconnect ghz@bobble:/zspace/pi/ghz /import/home/ghz'
    when: ansible_system == 'OpenBSD'
    tags:
      - sshfs
