# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

    - name: update, upgrade
      apt:
        upgrade: full
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: autoclean
      apt:
        autoclean: yes
      when: ansible_os_family == 'Debian'

    - name: autoremove
      apt:
        autoremove: yes
      when: ansible_os_family == 'Debian'

    - name: update
      apk:
        available: true
        upgrade: true
      when: ansible_os_family == 'Alpine'
