# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: no
  user: root

  tasks:

  - name: remove old pre-rsnaps backup cron job
    cron:
      name: backup
      state: absent
    when: inventory_hostname in groups['pis']
