# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

  - name: update, upgrade
    apt:
      upgrade: full
      update_cache: yes
    tags:
      - update

  - name: add packages
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - git
      - zsh
      - figlet
      - rsync
      - bsd-mailx
      - locate
      - vim
      - postfix
      - ufw
    tags:
      - packages

  - name: set hostname
    hostname:
      name: '{{ inventory_hostname }}'
    tags:
      - hostname

  - name: disable wank
    systemd:
      name: '{{ item }}'
      state: stopped
      enabled: no
    with_items:
      # - dbus
      # - dbus.socket
      - avahi-daemon
      - avahi-daemon.socket
      - triggerhappy
    tags:
      - wank

  - name: pull mdns noise
    lineinfile:
      dest: /etc/nsswitch.conf
      regexp: 'hosts:'
      line: 'hosts:		files dns'
    tags:
      - nss

  - name: pull pi user if it's still there
    user:
      name: pi
      state: absent

  - name: pull pi group if it exists
    group:
      name: pi
      state: absent

  - name: add me group
    group:
      name: ghz
      state: present

  - name: add backup tunnel group
    group:
      name: bkt0
      state: present
    when: inventory_hostname in groups['wxps']

  - name: add me
    user:
      name: ghz
      uid: 1000
      home: /home/ghz
      group: ghz
      groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
      shell: /usr/bin/zsh

  - name: add backup tunnel user
    user:
      name: bkt0
      home: /home/bkt0
      group: bkt0
    when: inventory_hostname in groups['wxps']

  - name: add backup tunnel .ssh dir
    file:
      path: /home/bkt0/.ssh
      owner: bkt0
      group: bkt0
      state: directory
      mode: 0700
    when: inventory_hostname in groups['wxps']

  - name: add .forward
    lineinfile:
      dest: /root/.forward
      create: yes
      line: ghz@darkdata.org
      owner: root
      group: root
      mode: 0644

  - name: add figlet hostname to motd
    shell: figlet `hostname -s` > /etc/motd

  - name: add root scripts dir
    file:
      path: /root/scripts
      owner: root
      group: root
      state: directory
      mode: 0755

  - name: template (kinda) backup script (pis)
    template:
      src: /home/ghz/scripts/gen_pi_bk
      dest: /root/scripts/gen_pi_bk
      owner: root
      group: root
      mode: 0755
    when: inventory_hostname in groups['pis']

  - name: template (kinda) backup script (weather probes)
    template:
      src: /home/ghz/scripts/wxp_pi_bk
      dest: /root/scripts/gen_pi_bk
      owner: root
      group: root
      mode: 0755
    when: inventory_hostname in groups['wxps']

  - name: template (kinda) weather probe backup tunnel pub key
    template:
      src: /home/ghz/ansible_playbooks/plates/bkfs0_ed25519.pub
      dest: /home/bkt0/.ssh/authorized_keys
      owner: bkt0
      group: bkt0
      mode: 0600
    when: inventory_hostname in groups['wxps']

  - name: template (kinda) netcheck script
    template:
      src: /home/ghz/scripts/netcheck
      dest: /root/scripts/netcheck
      owner: root
      group: root
      mode: 0755

  - name: template (kinda) .vimrc
    template:
      src: /home/ghz/env/.vimrc
      dest: /root/.vimrc
      owner: root
      group: root
      mode: 0644
    tags:
      - vimrc

  - name: add path to crontab
    cron:
      env: yes
      name: PATH
      value: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

  - name: add netcheck cron entry
    cron:
      name: netcheck
      minute: "*/13"
      hour: "*"
      day: "*"
      weekday: "*"
      month: "*"
      user: root
      job: "/root/scripts/netcheck"

  - name: add backup cron job
    cron:
      name: backup
      minute: "{{ 59 | random(seed=inventory_hostname) }}"
      hour: "{{ 5 | random(seed=inventory_hostname) }}"
      day: "*"
      weekday: "*"
      month: "*"
      user: root
      job: "/root/scripts/gen_pi_bk"

  - name: turn off hdmi to save power
    lineinfile:
      dest: /etc/rc.local
      insertbefore: 'exit 0'
      line: /usr/bin/tvservice -o

  - name: allow port 22
    ufw:
      state: enabled
      rule: allow
      port: 22
      proto: tcp
    tags:
      - fw

  - name: stop spamming our ring buffer
    ufw:
      logging: off
    tags:
      - fw

  - name: sort locales (1/2)
    locale_gen:
      name: en_US.UTF-8
      state: present
    tags:
      - locale

  - name: sort locales (2/2)
    locale_gen:
      name: en_GB.UTF-8
      state: absent
    tags:
      - locale

  - name: set timezone to utc
    timezone:
      name: UTC

  - name: template host
    template:
      src: /home/ghz/ansible_playbooks/plates/post_plate
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 644
    tags:
      - mail

  - name: reload postfix
    service:
      name: postfix
      state: reloaded
    tags:
      - mail

  - name: test mail schicken
    shell: "date | mail -s $(hostname) ghz@darkdata.org"
    tags:
      - mail
      - testmail
