# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

  - name: install packages (Debian)
    apt:
      name: [ unattended-upgrades, apt-listchanges ]
      update_cache: yes
      state: present
    when: ansible_os_family == 'Debian'
    tags:
      - packages

  - name: template unattended-upgrades config (Debian)
    template:
      src: /home/ghz/repos/ansible_playbooks/plates/50unattended-upgrades
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: 0644
    when: ansible_os_family == 'Debian'
    tags:
      - unattended

  - name: restart unattended-upgrades service (Debian)
    service:
      name: unattended-upgrades
      state: restarted
    when: ansible_os_family == 'Debian'
    tags:
      - unattended

  - name: add updates cron entry (Alpine)
    cron:
      name: updates
      minute: "16   "
      hour: "01   "
      day: "*   "
      weekday: "*   "
      month: "*   "
      user: root
      job: "apk -U upgrade"
    when: ansible_os_family == 'Alpine'
    tags:
      - cron

  - name: add system upgrades cron entry (OpenBSD)
    cron:
      name: system upgrades
      minute: "~	"
      hour: "~	"
      day: "*	"
      month: "*	"
      weekday: "5	"
      job: "sysupgrade"
    when: ansible_os_family == 'OpenBSD'
    tags:
      - cron

  - name: add package upgrades cron entry (OpenBSD)
    cron:
      name: package upgrades
      minute: "~	"
      hour: "~	"
      day: "*	"
      month: "*	"
      weekday: "*	"
      job: "pkg_add -u"
    when: ansible_os_family == 'OpenBSD'
    tags:
      - cron

  - name: add system patches cron entry (OpenBSD)
    cron:
      name: system patches
      minute: "~	"
      hour: "*/8	"
      day: "*	"
      month: "*	"
      weekday: "*	"
      job: "syspatch"
    when: ansible_os_family == 'OpenBSD'
    tags:
      - cron

  - name: config ntpd (OpenBSD)
    copy:
      src: plates/upgrade.site
      dest: /upgrade.site
      owner: root
      mode: 0755
    when: ansible_system == 'OpenBSD'
    tags:
      - updates
