# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: pis
  gather_facts: no
  user: root

  tasks:

  - name: blacklist wlan modules
    kernel_blacklist:
      name: '{{ item }}'
      state: absent
    with_items:
      - brcmfmac
      - brcmutil

  - name: pull wlan modules
    modprobe:
      name: '{{ item }}'
      state: absent
    with_items:
      - brcmfmac
      - brcmutil

  - name: disable wpa_supplicant
    systemd:
      name: wpa_supplicant
      state: stopped
      enabled: no
