# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: no
  user: ghz

  tasks:

  - name: add path to crontab
    cron:
      env: yes
      name: PATH
      value: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
      user: ghz

  - name: add home to crontab (wxps)
    cron:
      env: yes
      name: HOME
      value: /home/ghz
      user: ghz
    when: inventory_hostname in groups['wxps']

  - name: add home to crontab (pis)
    cron:
      env: yes
      name: HOME
      value: /import/home/ghz
      user: ghz
    when: inventory_hostname in groups['pis']

  - name: add temperature cron entry to non weather pis
    cron:
      name: box_temp
      minute: "*	"
      hour: "*	"
      day: "*	"
      weekday: "*	"
      month: "*	"
      user: ghz
      job: "/import/home/ghz/repos/scripts/box_temp.go"
    when: inventory_hostname in groups['pis']

  - name: add temperature cron entry to weather pis
    cron:
      name: box_temp
      minute: "*	"
      hour: "*	"
      day: "*	"
      weekday: "*	"
      month: "*	"
      user: ghz
      job: "/home/ghz/repos/scripts/box_temp.go"
    when: inventory_hostname in groups['wxps']
