# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---
- hosts: pis
  gather_facts: no
  user: root

  tasks:

  - name: add sshfs packages
    apt:
      name: sshfs
      state: present
    tags:
      - packages

  - name: add mount point dir
    file:
      dest: /import/home/ghz
      owner: ghz
      group: ghz
      state: directory
      mode: 0755

  - name: make sure root as a key
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_type: ed25519

  - name: add sshfs mount point
    mount:
      name: /import/home/ghz
      src: ghz@fs0:/mnt/violet/pi/ghz
      fstype: fuse.sshfs
      opts: rw,nosuid,nodev,allow_other
      state: mounted

  - name: swap arond my home
    user:
      name: ghz
      home: /import/home/ghz
