# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

  - name: add packages
    apt:
      name: [git, zsh, figlet, rsync, bsd-mailx, locate, vim, postfix, ufw, tcpdump, feh, ipython, python-matplotlib, python-numpy, aptitude, tmux, cu, openntpd, miscfiles, rdate, x11-apps, dnsutils]
      update_cache: yes
      state: present
    tags:
      - packages

  - name: update, upgrade
    apt:
      upgrade: full
      update_cache: yes
    tags:
      - update

  - name: set hostname
    hostname:
      name: '{{ inventory_hostname }}'
    tags:
      - hostname

  - name: disable wank
    systemd:
      name: '{{ item }}'
      state: stopped
      enabled: no
    with_items:
      # - dbus
      # - dbus.socket
      - avahi-daemon
      - avahi-daemon.socket
      - triggerhappy
    tags:
      - wank

  - name: pull mdns noise
    lineinfile:
      dest: /etc/nsswitch.conf
      regexp: 'hosts:'
      line: 'hosts:		files dns'
    tags:
      - nss

  - name: pull pi user if it's still there
    user:
      name: pi
      state: absent

  - name: pull pi group if it exists
    group:
      name: pi
      state: absent

  - name: add me group
    group:
      name: ghz
      state: present

  - name: add me
    user:
      name: ghz
      uid: 1000
      group: ghz
      groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
      shell: /usr/bin/zsh

  - name: sort homedir
    user:
      name: ghz
      home: /home/ghz
    when: inventory_hostname in groups['wxps']

  # home creation will be done by work-around-fucking-systemd playbook
  # create_home: no and skell appear to have no effect.
  # i haven't figured out how to set a home, but not create it or fill it will bullshit.
  # so work around this by just deleting it in the sshfs playbook.
  - name: sort homedir
    user:
      name: ghz
      create_home: no
      skeleton: /dev/null
      home: /import/home/ghz
    when: inventory_hostname in groups['pis']

  - name: add .forward
    lineinfile:
      dest: /root/.forward
      create: yes
      line: ghz@darkdata.org
      owner: root
      group: root
      mode: 0644

  - name: tell OpenNTPd to set time on boot
    lineinfile:
      path: /etc/default/openntpd
      regexp: '^DAEMON_OPTS='
      line: 'DAEMON_OPTS="-sf /etc/openntpd/ntpd.conf"'
    tags:
      - ntp_s

  - name: add figlet hostname to motd
    shell: figlet `hostname -s` > /etc/motd

  - name: add root scripts dir
    file:
      path: /root/scripts
      owner: root
      group: root
      state: directory
      mode: 0755

  - name: Set up multiple authorized keys
    authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - /home/ghz/ansible_playbooks/plates/rsnap_ed25519.pub
      - /home/ghz/.ssh/id_ed25519.pub

  - name: add my key
    authorized_key:
      user: ghz
      state: present
      key: "{{ lookup('file', '/home/ghz/.ssh/id_ed25519.pub') }}"
    when: inventory_hostname in groups['wxps']
    tags:
      - keys

  - name: template (kinda) netcheck script
    template:
      src: /home/ghz/scripts/netcheck
      dest: /root/scripts/netcheck
      owner: root
      group: root
      mode: 0755

  - name: template (kinda) .vimrc
    template:
      src: /home/ghz/env/.vimrc
      dest: /root/.vimrc
      owner: root
      group: root
      mode: 0644
    tags:
      - vimrc

  - name: add path to crontab
    cron:
      env: yes
      name: PATH
      value: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

  - name: add netcheck cron entry
    cron:
      name: netcheck
      minute: "*/13"
      hour: "*"
      day: "*"
      weekday: "*"
      month: "*"
      user: root
      job: "/root/scripts/netcheck"

#  this has bitten me in the ass when i try to rescue a pie more times than i care to think about
#  - name: turn off hdmi to save power
#    lineinfile:
#      dest: /etc/rc.local
#      insertbefore: 'exit 0'
#      line: /usr/bin/tvservice -o

  - name: allow port 22
    ufw:
      state: enabled
      rule: allow
      port: '22'
      proto: tcp
    tags:
      - fw

  - name: stop spamming our ring buffer
    ufw:
      logging: 'off'
    tags:
      - fw

  - name: sort locales (1/2)
    locale_gen:
      name: en_US.UTF-8
      state: present
    tags:
      - locale

  - name: sort locales (2/2)
    locale_gen:
      name: en_GB.UTF-8
      state: absent
    tags:
      - locale

  - name: set timezone to utc
    timezone:
      name: UTC

  - name: template postfix config
    template:
      src: /home/ghz/ansible_playbooks/plates/post_plate
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 644
    tags:
      - mail

  - name: reload postfix
    service:
      name: postfix
      state: reloaded
    tags:
      - mail

  - name: test mail schicken
    shell: "date | mail -s $(hostname) ghz@darkdata.org"
    tags:
      - mail
      - testmail
