# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

    - name: make sure we have main and community repos for (Alpine)
      template:
        src: plates/alp_repos
        dest: /etc/apk/repositories
        owner: root
        group: root
        mode: 0644
      when: ansible_facts['os_family'] == 'Alpine'
      tags:
        - packages
        - repos

    - name: update, upgrade (Debian)
      apt:
        upgrade: full
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - updates
        - packages

    - name: autoclean (Debian)
      apt:
        autoclean: yes
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - updates
        - packages

    - name: autoremove (Debian)
      apt:
        autoremove: yes
      when: ansible_facts['os_family'] == 'Debian'
      tags:
        - updates
        - packages

    - name: update (Alpine)
      apk:
        upgrade: true
        update_cache: true
      when: ansible_facts['os_family'] == 'Alpine'
      tags:
        - updates
        - packages

    - name: update (OpenBSD)
      openbsd_pkg:
        name: '*'
        state: latest
      when: ansible_facts['os_family'] == 'OpenBSD'
      tags:
        - updates
        - packages
