# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---
- hosts: pis
  gather_facts: no
  user: root

  tasks:

  - name: add nfs packages
    apt:
      name: nfs-common
      state: present
    tags:
      - packages

  - name: add mount point dir
    file:
      dest: /import/home/ghz
      owner: ghz
      group: ghz
      state: directory
      mode: 0755

  - name: enable and start nfs
    service:
      name: '{{ item }}'
      state: started
      enabled: yes
    with_items:
      - rpcbind
      - nfs-common

  - name: add nfs mount point
    mount:
      name: /import/home/ghz
      src: fs0:/mnt/violet/pi/ghz
      fstype: nfs
      opts: rw,nolock
      state: mounted

  - name: swap arond my home
    user:
      name: ghz
      home: /import/home/ghz
