# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: pis
  gather_facts: yes
  user: root

  tasks:

  - name: disable wpa_supplicant
    systemd:
      name: wpa_supplicant
      state: stopped
      enabled: no
    when: ansible_os_family == 'Debian'

  - name: blacklist wlan modules
    kernel_blacklist:
      name: '{{ item }}'
      state: present
    with_items:
      - brcmfmac
      - brcmutil
      - rfkill

  # modprobe -r doesn't work on alpine for some reason.
  # so just reply on the blacklist above for now.
  - name: pull wlan modules
    modprobe:
      name: '{{ item }}'
      state: absent
    with_items:
      - brcmfmac
      - brcmutil
    when: ansible_os_family == 'Debian'

  - name: remove packages
    apt:
      name: [ rfkill ]
      update_cache: yes
      state: absent
    tags:
      - packages
      - cleanup
    when: ansible_os_family == 'Debian'
