# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

  - name: disable bluetooth services
    systemd:
      name: '{{ item }}'
      state: stopped
      enabled: no
    with_items:
      - bluetooth
      - hciuart
    ignore_errors: true
    when: ansible_os_family == 'Debian'

  - name: blacklist bt modules
    kernel_blacklist:
      name: '{{ item }}'
      state: present
    with_items:
      - btbcm
      - hci_uart
      - bnep
      - bluetooth
      - rfkill
    when: ansible_system == 'Linux'

  # modprobe -r doesn't work on alpine for some reason
  # but the blacklist from above works, so these will be
  # gone on the next reboot. which is good enough for now.
  - name: pull bt modules
    modprobe:
      name: '{{ item }}'
      state: absent
    with_items:
      - hci_uart
      - btbcm
      - bnep
      - bluetooth
    ignore_errors: true
    when: ansible_os_family == 'Debian'
