# vim:set tabstop=2 softtabstop=2 shiftwidth=2 expandtab:
---

- hosts: all
  gather_facts: yes
  user: root

  tasks:

  - name: template postfix config
    template:
      src: /home/ghz/ansible_playbooks/plates/post_plate
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 0644
    tags:
      - mail

  - name: reload postfix
    service:
      name: postfix
      state: reloaded
    tags:
      - mail

  - name: add .forward
    lineinfile:
      dest: /root/.forward
      create: yes
      line: ghz@darkdata.org
      owner: root
      group: root
      mode: 0644
    tags:
      - mail

  - name: test mail schicken
    shell: "date | mail -s $(hostname) root"
    tags:
      - mail
      - testmail
